fix: log on unsuccessful responses
rperryng/graphql-ruby-hive pull request #45
Opened 2024-12-04 21:37 UTC by al-yanna

2024-12-04 22:04 UTC, al-yanna commented on lib/graphql-hive/client.rb
> +        parsed_body["errors"].map { |error| "path: #{error["path"]}, message: #{error["message"]}" }.join(", ")
"path" is the location of the error within the JSON structure of the request. 
 
 for example, if there is an error in the `metadata: client` property, it will be 
 ```
 "path": "/operations/0/metadata/client"
 ```

2024-12-05 15:09 UTC, aryascripts approved these changes
Looks good! Just a small nit about `response.code`

2024-12-05 15:09 UTC, aryascripts commented on lib/graphql-hive/client.rb
> +        if response.code.to_i >= 400 && response.code.to_i < 500
```suggestion
        code = response.code.to_i
        if code >= 400 && code < 500
```

2024-12-05 16:16 UTC, al-yanna commented on lib/graphql-hive/client.rb
> +        parsed_body["errors"].map { |error| "path: #{error["path"]}, message: #{error["message"]}" }.join(", ")
it would look something like this, depending on the error: 
![image](https://github.com/user-attachments/assets/8f3f7318-21e4-476e-b010-550c89bfe070)

2024-12-05 17:44 UTC, al-yanna commented
Converted to draft, merge https://github.com/rperryng/graphql-ruby-hive/pull/46 first to fix bug in version 0.5.2

2024-12-09 19:40 UTC, al-yanna commented on lib/graphql-hive/client.rb
> +        if code >= 400 && code < 500
```suggestion
        @options[:logger].info("Response: #{response.code} - #{response.message}")

        code = response.code.to_i
        if code >= 400 && code < 500
```

2024-12-17 16:46 UTC, al-yanna commented on lib/graphql-hive/client.rb
> +        @options[:logger].info("Response: #{response.code} - #{response.message}")
```suggestion
```

2024-12-18 15:42 UTC, cassidycodes requested changes
Thank you for doing this. Can you please add tests for the logging you've added.

2024-12-19 15:04 UTC, cassidycodes approved these changes

2024-12-19 15:40 UTC, al-yanna commented
@rperryng this PR is ready to be merged! 🙏

2024-12-21 17:45 UTC, merged